name: Publish release

# Publish release to Central Repository
on: workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Java and Maven
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - id: install-secret-key
        name: Install gpg secret key
        run: |
          cat <(echo -e "${{ secrets.GPG_PRIVATE_KEY }}") | gpg --batch --import --passphrase "${{ secrets.GPG_PRIVATE_KEY_PASSWORD }}"
          gpg --list-secret-keys --keyid-format LONG

      - name: Publish to Central Repository
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        run: mvn deploy -e --batch-mode --no-transfer-progress --update-snapshots -Dgpg.passphrase=${{ secrets.GPG_PRIVATE_KEY_PASSWORD }} -s deploy-settings.xml
