name: Test last commit

# Run workflow on commits to any branch except `master`
on: push

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Java and Maven
        uses: actions/setup-java@v1
        with:
          java-version: 8


      - name: Testing
        run: mvn test --batch-mode --no-transfer-progress --update-snapshots